import assert from "node:assert/strict";
import { parseAnalyse, buildDecisionSummary } from "./analyseSummary";
import type { DeepDecision } from "./deepDecision";
assert.deepEqual(parseAnalyse("/analyse@bot   btc-usd detail 5y 1d"), {symbol:"BTC-USD", interval:"1d", range:"5y", detail:true});
assert.equal(parseAnalyse("/analyse NVDA").range, "5y");
assert.equal(parseAnalyse("/analyse NVDA 1d").range, "1y");
assert.equal(parseAnalyse("/analyse NVDA detail max 1wk").range, "max");
for (const text of ["/analyse", "/analyse NVDA 1h", "/analyse NVDA 1d 1w", "/analyse NVDA 1y 5y", "/analyse *NVDA*"]) assert.throws(() => parseAnalyse(text));
const base: DeepDecision = { status:"WATCH", direction:"LONG", frozen:false, zone:null, trigger:null, invalidation:null, target:null, cExtreme:null, entry:null, potentialR:null, snapshotId:null, asOf:"2026-10-01", dataHash:"fixture", engineVersion:"171", createdAt:null };
const summary = (d: DeepDecision) => buildDecisionSummary({trend:"bearish", asOf:"2026-10-02", decision:d, structures:[], symbol:"BTC-USD"});
assert.match(summary(base), /Trend: BEARISH/);
assert.match(summary(base), /Korrektur: Nicht bestätigt/);
assert.match(summary(base), /ABWARTEN/);
assert.match(summary(base), /1,2-Setup: Keines bestätigt/);
assert.match(summary(base), /AI_CAPITAL_ROTATION/);
assert.match(summary(base), /UNKNOWN/);
const candidate = {...base, status:"CANDIDATE" as const, trigger:100, invalidation:90, target:120};
assert.match(summary(candidate), /Korrektur: Abschluss-Kandidat/);
assert.match(summary(candidate), /KAUF.*BEDINGT/);
assert.match(summary({...candidate, status:"CONFIRMED"}), /kein neuer Einstiegspreis/);
assert.match(summary({...candidate, direction:"SHORT"}), /VERKAUF.*SHORT/);
console.log("Analyse: argument validation, correction uncertainty and canonical trade options passed.");
